### ISSUE TITLE
How to read 32bit register

### ISSUE THREAD

**Issue by yiannosi** [DFRobot/DFRobot_RTU#1]
Hi..
How can I read a 32bit length single register?
Can you give an example please?

**Comment by Arya11111** [comment]
According to the Modbus RTU protocol specification, it does not directly support 32-bit registers. However, it is possible to use consecutive 16-bit registers to store a 32-bit value. Could you please provide more detailed information about the communication protocol of the product you are working with? With that information, I might be able to assist you in finding a solution.

抱歉，Modbus RTU协议规范，它不直接支持32bit的寄存器，但是它可以使用连续的16位寄存器来存储一个32位的值，你能提供更加详细的使用细节么(比如你要操作产品的协议格式)，我或许可以帮你想一个办法。
